version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: patchy-frontend
    ports:
      - "11777:11777"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DOCKER_PATH=${DOCKER_PATH:-/var/lib/docker}  # Default path with override option
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ${DOCKER_PATH:-/var/lib/docker}:/docker:ro  # Mount Docker path as read-only
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11777"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=patchy"
      - "com.docker.compose.service=frontend"

networks:
  default:
    name: patchy-network
    driver: bridge

volumes:
  node_modules: