version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patchy-app
    ports:
      - "11777:11777"
      - "11778:11778"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=11778
      - DOCKER_PATH=/var/run/docker.sock
      - VITE_API_URL=http://localhost:11778
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11777"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=patchy"

networks:
  default:
    name: patchy-network
    driver: bridge