version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: patchy-frontend
    ports:
      - "11777:11777"
      - "11778:11778"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_PORT=11778
      - VITE_API_URL=http://localhost:11778/api
      - DOCKER_SOCKET=${DOCKER_SOCKET:-/var/run/docker.sock}
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11777/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=patchy"
      - "com.docker.compose.service=frontend"

networks:
  default:
    name: patchy-network
    driver: bridge